all:
	g++ uva929.cpp -o ./temp/uva929
	g++ uva10986.cpp -o ./temp/uva10986
	g++ uva10048.cpp -o ./temp/uva10048
	g++ uva821.cpp -o ./temp/uva821
	g++ uva10000.cpp -o ./temp/uva10000
	g++ uva558.cpp -o ./temp/uva558
	g++ uva10801.cpp -o ./temp/uva10801
	g++ uva11374.cpp -o ./temp/uva11374
