all:
	g++ uva10034.cpp -o ./temp/uva10034
	g++ uva10034_2.cpp -o ./temp/uva10034_2
	g++ uva7001.cpp -o ./temp/uva7001
	g++ uva1208.cpp -o ./temp/uva1208
	g++ uva10369.cpp -o ./temp/uva10369
	g++ uva534.cpp -o ./temp/uva534
	g++ uva11733.cpp -o ./temp/uva11733
	g++ uva1395.cpp -o ./temp/uva1395
